//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PNNLOmics.UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PNNLOmics.UnitTests.DataResources", typeof(DataResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature_Index	Monoisotopic_Mass	Average_Mono_Mass	UMC_MW_Min	UMC_MW_Max	Scan_Start	Scan_End	Scan	UMC_Member_Count	Max_Abundance	Abundance	Class_Rep_MZ	Class_Rep_Charge	Charge_Max	Drift_Time	Conformation_Fit_Score
        ///1	1128.65675	1128.65675	1128.63421	1128.67506	2	17	7	18	2443	45200	565.33955	2	2	28.086	0
        ///5	1771.01446	1771.01446	1770.98789	1771.04988	6	12	12	9	1998	15793	591.35565	3	3	27.703	0
        ///9	1494.68859	1494.68859	1494.66722	1494.7117	29	36	36	12	1845	28433	748.34739	2	2	31.109	0
        ///16	1898.89558	1898.89558 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string featuresA {
            get {
                return ResourceManager.GetString("featuresA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to featuresA.txt.
        /// </summary>
        internal static string featuresAFilePath {
            get {
                return ResourceManager.GetString("featuresAFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature_Index	Monoisotopic_Mass	Average_Mono_Mass	UMC_MW_Min	UMC_MW_Max	Scan_Start	Scan_End	Scan	UMC_Member_Count	Max_Abundance	Abundance	Class_Rep_MZ	Class_Rep_Charge	Charge_Max	Drift_Time	Conformation_Fit_Score
        ///1	400.33401	400.33401	400.329	400.34062	1	18	3	210	7954	5919732	401.34014	1	1	31.872	0
        ///2	444.11317	444.11317	444.10904	444.11955	1	5	4	20	2356	129138	445.11727	1	1	28.366	0
        ///3	536.15910	536.15910	536.14322	536.175	1	57	21	359	4049	623892	537.16403	1	1	32.731	0
        ///9	643.49235	643.49235	643.47276	643 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string featuresB {
            get {
                return ResourceManager.GetString("featuresB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to featuresB.txt.
        /// </summary>
        internal static string featuresBFilePath {
            get {
                return ResourceManager.GetString("featuresBFilePath", resourceCulture);
            }
        }
    }
}
